import crypto from 'crypto';
export const STATES=Object.freeze(['propagation','vegetative','flowering','harvest_hold','tested','packaged','transferred','destroyed','recalled']);
export const TRANSITIONS=Object.freeze({propagation:['vegetative','destroyed'],vegetative:['flowering','destroyed','recalled'],flowering:['harvest_hold','destroyed','recalled'],harvest_hold:['tested','destroyed','recalled'],tested:['packaged','destroyed','recalled'],packaged:['transferred','destroyed','recalled'],transferred:['recalled'],destroyed:[],recalled:['destroyed']});
export const PROVIDERS=Object.freeze(['metrc','biotrack','lab','sensor','pos','identity']);
export class CultivationError extends Error{constructor(code,message,status=400){super(message);this.code=code;this.status=status;}}
export function tenantFor(user){if(!user?.id)throw new CultivationError('AUTH_REQUIRED','Authentication required',401);return String(user.facility_id||user.tenant_id||user.tenantId||`personal:${user.id}`);}
export function requireRole(user,roles){if(!roles.includes(user.role))throw new CultivationError('ROLE_FORBIDDEN',`Role ${user.role||'unknown'} is not authorized`,403);}
export function normalizeLot(input={}){const required=['facilityId','batchId','tagId','jurisdiction','cultivar','startedAt'];const missing=required.filter(k=>!input[k]);if(missing.length)throw new CultivationError('INVALID_LOT',`Missing: ${missing.join(', ')}`);if(Number.isNaN(Date.parse(input.startedAt)))throw new CultivationError('INVALID_TIME','startedAt must be ISO-8601');return{facilityId:String(input.facilityId),batchId:String(input.batchId),tagId:String(input.tagId),jurisdiction:String(input.jurisdiction),cultivar:String(input.cultivar),startedAt:new Date(input.startedAt).toISOString(),sourcePlantTag:input.sourcePlantTag||null,quantity:Number(input.quantity||1),unit:input.unit||'plant'};}
export function validateTransition(current,next,user,evidence={}){if(!(TRANSITIONS[current]||[]).includes(next))throw new CultivationError('INVALID_TRANSITION',`Cannot move ${current} to ${next}`,409);const compliance=['compliance','manager','admin'];requireRole(user,next==='transferred'||next==='destroyed'||next==='recalled'?compliance:['operator','cultivator','compliance','manager','admin']);if(next==='tested'&&(!evidence.labResultId||!evidence.chainOfCustodyId||evidence.passed!==true))throw new CultivationError('LAB_RELEASE_REQUIRED','Passing lab result and chain of custody are required');if(next==='packaged'&&(!evidence.inventoryReconciliationId||Number(evidence.packagedQuantity)<=0||Number(evidence.wasteQuantity)<0))throw new CultivationError('RECONCILIATION_REQUIRED','Package and waste reconciliation are required');if(next==='transferred'&&(!evidence.manifestId||!evidence.destinationLicense||!evidence.approvedBy))throw new CultivationError('TRANSFER_APPROVAL_REQUIRED','Manifest, licensed destination, and approval are required');if(next==='destroyed'&&(!evidence.wasteManifestId||!Array.isArray(evidence.witnesses)||evidence.witnesses.length<2))throw new CultivationError('WASTE_WITNESSES_REQUIRED','Waste manifest and two witnesses are required');if(next==='recalled'&&!evidence.recallReason)throw new CultivationError('RECALL_REASON_REQUIRED','Recall reason required');}
export function idempotencyKey(key){if(!key||!/^[A-Za-z0-9._:-]{8,128}$/.test(key))throw new CultivationError('IDEMPOTENCY_REQUIRED','Valid Idempotency-Key required');return key;}
export const digest=(data)=>crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex');
